#!/usr/bin/env python3
"""Generate one fallback provider for every exported Arch glibc symbol."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, order=True)
class Export:
    name: str
    version: str
    kind: str
    size: int


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def exports(path: Path) -> set[Export]:
    output = subprocess.check_output(
        ["llvm-readelf", "--dyn-symbols", "--wide", str(path)],
        text=True,
        stderr=subprocess.DEVNULL,
    )
    result: set[Export] = set()

    for line in output.splitlines():
        columns = line.split()
        if len(columns) < 8 or columns[6] == "UND":
            continue
        kind = columns[3]
        if kind not in {"FUNC", "IFUNC", "OBJECT", "TLS"}:
            continue
        name = columns[7]
        if "@GLIBC_" not in name:
            continue
        name, version = name.split("@", 1)
        version = version.lstrip("@")
        if name.startswith("GLIBC_"):
            continue
        result.add(Export(name, version, kind, int(columns[2])))

    return result


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_glibc_stubs.py GLIBC_PACKAGE OUTPUT")

    package = Path(sys.argv[1])
    output = Path(sys.argv[2])

    with tempfile.TemporaryDirectory(prefix="dlfcn-glibc-") as temporary:
        root = Path(temporary)
        subprocess.run(
            ["bsdtar", "-xpf", str(package), "-C", str(root)],
            check=True,
        )
        found: set[Export] = set()
        for path in sorted((root / "usr" / "lib").glob("*.so*")):
            if not path.is_file() or path.read_bytes()[:4] != b"\x7fELF":
                continue
            found.update(exports(path))

    lines = ["// Generated by dev/generate_glibc_stubs.py."]
    for index, symbol in enumerate(sorted(found)):
        kind = "FUNCTION" if symbol.kind in {"FUNC", "IFUNC"} else symbol.kind
        lines.append(
            f"GLIBC_{kind}_STUB("
            f"{index}, {quote(symbol.name)}, {quote(symbol.version)}, {symbol.size})"
        )
    lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(f"generated {len(found)} versioned glibc providers in {output}")


if __name__ == "__main__":
    main()
