#!/usr/bin/env python3
"""Generate factory providers for musl functions imported by an Arch DSO tree."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


UNSAFE_PREFIXES = (
    "pthread_",
    "sem_",
)
UNSAFE_NAMES = {
    "__tls_get_addr",
    "dladdr",
    "dlclose",
    "dlerror",
    "dlopen",
    "dlsym",
    "strerror_r",
}


def imported_glibc_symbols(root: Path) -> set[str]:
    result: set[str] = set()
    for path in sorted((root / "usr" / "lib").rglob("*")):
        if not path.is_file() or ".so" not in path.name:
            continue
        try:
            if path.read_bytes()[:4] != b"\x7fELF":
                continue
            output = subprocess.check_output(
                ["llvm-readelf", "--dyn-symbols", "--wide", str(path)],
                text=True,
                stderr=subprocess.DEVNULL,
            )
        except (OSError, subprocess.CalledProcessError):
            continue
        for line in output.splitlines():
            columns = line.split()
            if len(columns) >= 8 and columns[6] == "UND" and "@GLIBC_" in columns[7]:
                result.add(columns[7].split("@", 1)[0])
    return result


def archive_symbols(archive: Path) -> set[str]:
    output = subprocess.check_output(
        ["llvm-nm", "--defined-only", "--extern-only", str(archive)],
        text=True,
        stderr=subprocess.DEVNULL,
    )
    result: set[str] = set()
    for line in output.splitlines():
        match = re.match(r"^[0-9a-fA-F]+\s+[A-Za-z]\s+(.+)$", line)
        if match:
            result.add(match.group(1))
    return result


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(
            "usage: generate_host_symbols.py ARCH_ROOT MUSL_LIBC_A OUTPUT_CPP"
        )

    imported = imported_glibc_symbols(Path(sys.argv[1]))
    available = archive_symbols(Path(sys.argv[2]))
    direct = sorted(
        symbol
        for symbol in imported & available
        if symbol not in UNSAFE_NAMES
        and not symbol.startswith(UNSAFE_PREFIXES)
    )

    lines = [
        "// Generated by generate_host_symbols.py.",
        '#include "dlfcn.h"',
        "",
        "#include <stdint.h>",
        "",
        'extern "C" {',
    ]
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'    extern unsigned char HOST_{index}[] __asm__("{escaped}");'
        )
    lines.extend([
        "}",
        "",
        "namespace {",
        "    struct HostSymbol {",
        "        const char* name;",
        "        void* address;",
        "    };",
        "",
        "    const HostSymbol HOST_SYMBOLS[] = {",
    ])
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'        {{"{escaped}", reinterpret_cast<void*>(HOST_{index})}},'
        )
    lines.extend([
        "    };",
        "",
        "    struct RegisterHostSymbols {",
        "        RegisterHostSymbols() {",
        "            for (const auto& symbol : HOST_SYMBOLS) {",
        '                stub_dlregister("c", symbol.name, symbol.address);',
        "            }",
        "        }",
        "    } REGISTER_HOST_SYMBOLS;",
        "}",
        "",
    ])

    output = Path(sys.argv[3])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(f"generated {len(direct)} musl factory providers in {output}")


if __name__ == "__main__":
    main()
