#!/usr/bin/env python3
"""Generate factory providers for every symbol exported by musl."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def archive_symbols(archive: Path) -> set[str]:
    output = subprocess.check_output(
        ["llvm-nm", "--defined-only", "--extern-only", str(archive)],
        text=True,
        stderr=subprocess.DEVNULL,
    )
    result: set[str] = set()
    for line in output.splitlines():
        match = re.match(r"^[0-9a-fA-F]+\s+[A-Za-z]\s+(.+)$", line)
        if match:
            result.add(match.group(1))
    return result


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_host_symbols.py MUSL_LIBC_A OUTPUT_CPP")

    direct = sorted(archive_symbols(Path(sys.argv[1])))

    lines = [
        "// Generated by generate_host_symbols.py.",
        '#include "dlfcn.h"',
        "",
        "#include <stdint.h>",
        "",
        'extern "C" {',
    ]
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'    extern unsigned char HOST_{index}[] __asm__("{escaped}");'
        )
    lines.extend([
        "}",
        "",
        "namespace {",
        "    struct HostSymbol {",
        "        const char* name;",
        "        void* address;",
        "    };",
        "",
        "    const HostSymbol HOST_SYMBOLS[] = {",
    ])
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'        {{"{escaped}", reinterpret_cast<void*>(HOST_{index})}},'
        )
    lines.extend([
        "    };",
        "",
        "    struct RegisterHostSymbols {",
        "        RegisterHostSymbols() {",
        "            for (const auto& symbol : HOST_SYMBOLS) {",
        '                stub_dlregister("c", symbol.name, symbol.address);',
        "            }",
        "        }",
        "    } REGISTER_HOST_SYMBOLS;",
        "}",
        "",
    ])

    output = Path(sys.argv[2])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(f"generated {len(direct)} musl factory providers in {output}")


if __name__ == "__main__":
    main()
